export const authCostanti = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILURE:'LOGOUT_FAILURE',
    REGISTRAZIONE_REQUEST: "REGISTRAZIONE_REQUEST",
    REGISTRAZIONE_SUCCESS: "REGISTRAZIONE_SUCCESS",
    REGISTRAZIONE_FAILURE: "REGISTRAZIONE_FAILURE",
  };
  
  export const carrelloCostanti = {
    ADD_TO_CARRELLO_REQUEST: "ADD_TO_CARRELLO_REQUEST",
    ADD_TO_CARRELLO_SUCCESS: "ADD_TO_CARRELLO_SUCCESS",
    ADD_TO_CARRELLO_FAILURE: "ADD_TO_CARRELLO_FAILURE",
    RESET_CARRELLO: "RESET_CARRELLO",
  
    REMOVE_CARRELLO_ITEM_REQUEST: "REMOVE_CARRELLO_ITEM_REQUEST",
    REMOVE_CARRELLO_ITEM_SUCCESS: "REMOVE_CARRELLO_ITEM_SUCCESS",
    REMOVE_CARRELLO_ITEM_FAILURE: "REMOVE_CARRELLO_ITEM_FAILURE",
  };
  
  export const utenteCostanti = {
    ADD_UTENTE_ORDINE_REQUEST: "ADD_UTENTE_ORDINE_REQUEST",
    ADD_UTENTE_ORDINE_SUCCESS: "ADD_UTENTE_ORDINE_SUCCESS",
    ADD_UTENTE_ORDINE_FAILURE: "ADD_UTENTE_ORDINE_FAILURE",
  
    GET_UTENTE_ORDINE_REQUEST: "GET_UTENTE_ORDINE_REQUEST",
    GET_UTENTE_ORDINE_SUCCESS: "GET_UTENTE_ORDINE_SUCCESS",
    GET_UTENTE_ORDINE_FAILURE: "GET_UTENTE_ORDINE_FAILURE",
  
    GET_UTENTE_ORDINE_DETAILS_REQUEST: "GET_UTENTE_ORDINE_DETAILS_REQUEST",
    GET_UTENTE_ORDINE_DETAILS_SUCCESS: "GET_UTENTE_ORDINE_DETAILS_SUCCESS",
    GET_UTENTE_ORDINE_DETAILS_FAILURE: "GET_UTENTE_ORDINE_DETAILS_FAILURE",
  };
export const categorieCostanti = {
    ADD_NEW_CATEGORIE_REQUEST:'ADD_NEW_CATEGORIE_REQUEST',
    ADD_NEW_CATEGORIE_SUCCESS:'ADD_NEW_CATEGORIE_SUCCESS',
    ADD_NEW_CATEGORIE_FAILURE:'ADD_NEW_CATEGORIE_FAILURE',
    UPDATE_CATEGORIE_REQUEST:'UPDATE_CATEGORIE_REQUEST',
    UPDATE_CATEGORIE_SUCCESS:'UPDATE_CATEGORIE_SUCCESS',
    UPDATE_CATEGORIE_FAILURE:'UPDATE_CATEGORIE_FAILURE',
    GET_ALL_CATEGORIE_REQUEST:'GET_ALL_CATEGORIE_REQUEST',
    GET_ALL_CATEGORIE_SUCCESS:'GET_ALL_CATEGORIE_SUCCESS',
    GET_ALL_CATEGORIE_FAILURE:'GET_ALL_CATEGORIE_FAILURE',
    DELETE_CATEGORIE_REQUEST:'DELETE_CATEGORIE_REQUEST',
    DELETE_CATEGORIE_SUCCESS:'DELETE_CATEGORIE_SUCCESS',
    DELETE_CATEGORIE_FAILURE:'DELETE_CATEGORIE_FAILURE'

}

export const partiteCostanti = {
    GET_PARTITA_DETAILS_BY_ID_REQUEST:'GET_PARTITA_DETAILS_BY_ID_REQUEST',
    GET_PARTITA_DETAILS_BY_ID_SUCCESS:'GET_PARTITA_DETAILS_BY_ID_SUCCESS',
    GET_PARTITA_DETAILS_BY_ID_FAILURE:'GET_PARTITA_DETAILS_BY_ID_FAILURE',
    GET_PARTITA_PAGE_REQUEST:'GET_PARTITA_PAGE_REQUEST',
    GET_PARTITA_PAGE_SUCCESS:'GET_PARTITA_PAGE_SUCCESS',
    GET_PARTITA_PAGE_FAILURE:'GET_PARTITA_PAGE_FAILURE',
    GET_PARTITA_BY_SLUG:'GET_PARTITA_BY_SLUG',
}
